In [1]:
import pandas as pd
import os 
usuario = os.getlogin()

In [2]:
informe = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Comando Florence Nightingale\Proyectos\78_transicion sistemas prod\informe\tabla_resumen\base_clues_sistemas_completa.parquet")

In [3]:
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [4]:
clues.columns

Index(['clues_imb', 'clues_ssa_y_sme', 'categoria_gerencial_uas',
       'categoria_gerencial', 'categoria_gerencial_ampliada',
       'clave_de_la_entidad', 'entidad', 'clave_del_municipio', 'municipio',
       'localidad', 'clave_de_la_localidad', 'nombre_de_la_unidad',
       'nombre_comercial', 'estatus_de_operacion', 'nivel_atencion',
       'clave_de_tipologia', 'nombre_de_tipologia', 'clave_de_subtipologia',
       'nombre_de_subtipologia', 'estrato_unidad', 'cve_ro', 'nombre_region',
       'latitud', 'longitud', 'organ_ro', 'FECHA DE INICIO DE OPERACION',
       'tipo_hbc'],
      dtype='object')

In [5]:
informe = informe.rename(columns={"clues": "clues_imb"})

In [6]:
informe

,clues_imb,pqx_reportados_ece,pqx_incorporados_ece,pqx_reportados_sinba,pqx_totales,reporta_pqx_ece,reporta_pqx_sinba,consultas_reportadas_ece,consultas_incorporadas_ece,consultas_reportadas_sinba,consultas_totales,reporta_consulta_ece,reporta_consulta_sinba,egresos_reportados_ece,egresos_incorporados_ece,egresos_reportados_sinba,egresos_totales,reporta_egreso_ece,reporta_egreso_sinba
0,BCIMB000010,0.0,0.0,2438.0,2438.0,False,True,0.0,0.0,30444.0,30444.0,False,True,0.0,0.0,4020.0,4020.0,False,True
1,BCIMB000355,0.0,0.0,1094.0,1094.0,False,False,0.0,0.0,6983.0,6983.0,False,True,0.0,0.0,1562.0,1562.0,False,True
2,BCIMB000623,0.0,0.0,0.0,0.0,False,False,0.0,0.0,12994.0,12994.0,False,True,0.0,0.0,0.0,0.0,False,False
3,BCIMB000676,0.0,0.0,978.0,978.0,False,True,0.0,0.0,2272.0,2272.0,False,True,0.0,0.0,910.0,910.0,False,True
4,BCIMB000734,0.0,0.0,3175.0,3175.0,False,True,0.0,0.0,33489.0,33489.0,False,True,0.0,0.0,6866.0,6866.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,ZSIMB002015,0.0,0.0,198.0,198.0,False,True,0.0,0.0,8665.0,8665.0,False,True,0.0,0.0,271.0,271.0,False,True
587,ZSIMB002126,0.0,0.0,4046.0,4046.0,False,True,0.0,0.0,9089.0,9089.0,False,True,0.0,0.0,4127.0,4127.0,False,True
588,ZSIMB002213,0.0,0.0,0.0,0.0,False,False,0.0,0.0,10963.0,10963.0,False,True,0.0,0.0,273.0,273.0,False,True
589,ZSIMB002295,0.0,0.0,613.0,613.0,False,True,0.0,0.0,9677.0,9677.0,False,True,0.0,0.0,969.0,969.0,False,True
590,ZSIMB002481,0.0,0.0,3163.0,3163.0,False,True,0.0,0.0,17913.0,17913.0,False,True,0.0,0.0,3072.0,3072.0,False,True

In [7]:
hab_merge = (
    clues[["clues_imb", 'entidad', 'nombre_de_la_unidad']]

)
informe= informe.merge(hab_merge, on="clues_imb", how="left")

In [8]:
informe

,clues_imb,pqx_reportados_ece,pqx_incorporados_ece,pqx_reportados_sinba,pqx_totales,reporta_pqx_ece,reporta_pqx_sinba,consultas_reportadas_ece,consultas_incorporadas_ece,consultas_reportadas_sinba,...,reporta_consulta_ece,reporta_consulta_sinba,egresos_reportados_ece,egresos_incorporados_ece,egresos_reportados_sinba,egresos_totales,reporta_egreso_ece,reporta_egreso_sinba,entidad,nombre_de_la_unidad
0,BCIMB000010,0.0,0.0,2438.0,2438.0,False,True,0.0,0.0,30444.0,...,False,True,0.0,0.0,4020.0,4020.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL DE ENSENADA
1,BCIMB000355,0.0,0.0,1094.0,1094.0,False,False,0.0,0.0,6983.0,...,False,True,0.0,0.0,1562.0,1562.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL DE MEXICALI
2,BCIMB000623,0.0,0.0,0.0,0.0,False,False,0.0,0.0,12994.0,...,False,True,0.0,0.0,0.0,0.0,False,False,BAJA CALIFORNIA,HOSPITAL COMUNITARIO SAN FELIPE
3,BCIMB000676,0.0,0.0,978.0,978.0,False,True,0.0,0.0,2272.0,...,False,True,0.0,0.0,910.0,910.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL DE TECATE
4,BCIMB000734,0.0,0.0,3175.0,3175.0,False,True,0.0,0.0,33489.0,...,False,True,0.0,0.0,6866.0,6866.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL TIJUANA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,ZSIMB002015,0.0,0.0,198.0,198.0,False,True,0.0,0.0,8665.0,...,False,True,0.0,0.0,271.0,271.0,False,True,ZACATECAS,HOSPITAL COMUNITARIO SOMBRERETE
587,ZSIMB002126,0.0,0.0,4046.0,4046.0,False,True,0.0,0.0,9089.0,...,False,True,0.0,0.0,4127.0,4127.0,False,True,ZACATECAS,HOSPITAL DE LA MUJER
588,ZSIMB002213,0.0,0.0,0.0,0.0,False,False,0.0,0.0,10963.0,...,False,True,0.0,0.0,273.0,273.0,False,True,ZACATECAS,HOSPITAL DE ESPECIALIDADES DE SALUD MENTAL
589,ZSIMB002295,0.0,0.0,613.0,613.0,False,True,0.0,0.0,9677.0,...,False,True,0.0,0.0,969.0,969.0,False,True,ZACATECAS,HOSPITAL GENERAL LORETO
590,ZSIMB002481,0.0,0.0,3163.0,3163.0,False,True,0.0,0.0,17913.0,...,False,True,0.0,0.0,3072.0,3072.0,False,True,ZACATECAS,HOSPITAL GENERAL ZACATECAS LUZ GONZÁLEZ COSIO

In [9]:
informe

,clues_imb,pqx_reportados_ece,pqx_incorporados_ece,pqx_reportados_sinba,pqx_totales,reporta_pqx_ece,reporta_pqx_sinba,consultas_reportadas_ece,consultas_incorporadas_ece,consultas_reportadas_sinba,...,reporta_consulta_ece,reporta_consulta_sinba,egresos_reportados_ece,egresos_incorporados_ece,egresos_reportados_sinba,egresos_totales,reporta_egreso_ece,reporta_egreso_sinba,entidad,nombre_de_la_unidad
0,BCIMB000010,0.0,0.0,2438.0,2438.0,False,True,0.0,0.0,30444.0,...,False,True,0.0,0.0,4020.0,4020.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL DE ENSENADA
1,BCIMB000355,0.0,0.0,1094.0,1094.0,False,False,0.0,0.0,6983.0,...,False,True,0.0,0.0,1562.0,1562.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL DE MEXICALI
2,BCIMB000623,0.0,0.0,0.0,0.0,False,False,0.0,0.0,12994.0,...,False,True,0.0,0.0,0.0,0.0,False,False,BAJA CALIFORNIA,HOSPITAL COMUNITARIO SAN FELIPE
3,BCIMB000676,0.0,0.0,978.0,978.0,False,True,0.0,0.0,2272.0,...,False,True,0.0,0.0,910.0,910.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL DE TECATE
4,BCIMB000734,0.0,0.0,3175.0,3175.0,False,True,0.0,0.0,33489.0,...,False,True,0.0,0.0,6866.0,6866.0,False,True,BAJA CALIFORNIA,HOSPITAL GENERAL TIJUANA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,ZSIMB002015,0.0,0.0,198.0,198.0,False,True,0.0,0.0,8665.0,...,False,True,0.0,0.0,271.0,271.0,False,True,ZACATECAS,HOSPITAL COMUNITARIO SOMBRERETE
587,ZSIMB002126,0.0,0.0,4046.0,4046.0,False,True,0.0,0.0,9089.0,...,False,True,0.0,0.0,4127.0,4127.0,False,True,ZACATECAS,HOSPITAL DE LA MUJER
588,ZSIMB002213,0.0,0.0,0.0,0.0,False,False,0.0,0.0,10963.0,...,False,True,0.0,0.0,273.0,273.0,False,True,ZACATECAS,HOSPITAL DE ESPECIALIDADES DE SALUD MENTAL
589,ZSIMB002295,0.0,0.0,613.0,613.0,False,True,0.0,0.0,9677.0,...,False,True,0.0,0.0,969.0,969.0,False,True,ZACATECAS,HOSPITAL GENERAL LORETO
590,ZSIMB002481,0.0,0.0,3163.0,3163.0,False,True,0.0,0.0,17913.0,...,False,True,0.0,0.0,3072.0,3072.0,False,True,ZACATECAS,HOSPITAL GENERAL ZACATECAS LUZ GONZÁLEZ COSIO

In [10]:
# Infraestructura: resumen para cards por CLUES (Consultas, Procedimientos Quirurgicos y Egresos)
import json
from pathlib import Path

base_output = Path(r"C:\Users\jose.valdez\Downloads\reporteador\reporte-_angeles\public")
prev_infra_path = base_output / 'infraestructura_cards.json'
prev_infraestructura_cards = {}
if prev_infra_path.exists():
    try:
        with prev_infra_path.open('r', encoding='utf-8') as f:
            prev_infraestructura_cards = json.load(f)
    except Exception:
        prev_infraestructura_cards = {}

def to_bool(s: pd.Series) -> pd.Series:
    if s.dtype == bool:
        return s.fillna(False)
    txt = s.astype(str).str.strip().str.lower()
    return txt.isin(['true', '1', 'si', 'yes'])

def to_number(s: pd.Series) -> pd.Series:
    # 0.0 se interpreta como cero; 500.0 se conserva como valor positivo
    txt = s.astype(str).str.strip()
    txt = txt.str.replace(' ', '', regex=False)
    txt = txt.str.replace(',', '.', regex=False)
    return pd.to_numeric(txt, errors='coerce').fillna(0)

def first_non_empty(series: pd.Series) -> str:
    for val in series:
        txt = str(val).strip()
        if txt and txt.lower() != 'nan':
            return txt
    return ''

def to_int(value: object) -> int:
    try:
        return int(float(value))
    except Exception:
        return 0

def build_cards_payload(
    df: pd.DataFrame,
    indicador: str,
    cols_num: list[str],
    col_bool_ece: str,
    col_bool_sinba: str,
    resumen_cols: dict | None = None,
    previous_payload: dict | None = None,
) -> dict:
    required_cols = ['clues_imb', *cols_num, col_bool_ece, col_bool_sinba]
    if resumen_cols:
        required_cols.extend([resumen_cols['ece'], resumen_cols['sinba'], resumen_cols['total']])
    # Evita columnas duplicadas (ej. total y ece usando la misma columna)
    required_cols = list(dict.fromkeys(required_cols))

    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"[{indicador}] Faltan columnas en informe: {missing_cols}")

    tmp = df[required_cols].copy()
    tmp['entidad'] = df['entidad'] if 'entidad' in df.columns else ''
    tmp['nombre_de_la_unidad'] = df['nombre_de_la_unidad'] if 'nombre_de_la_unidad' in df.columns else ''

    tmp['ece_bool'] = to_bool(tmp[col_bool_ece])
    tmp['sinba_bool'] = to_bool(tmp[col_bool_sinba])

    for col in cols_num:
        tmp[f'{col}_num'] = to_number(tmp[col])

    if resumen_cols:
        tmp['resumen_ece_num'] = to_number(tmp[resumen_cols['ece']])
        tmp['resumen_sinba_num'] = to_number(tmp[resumen_cols['sinba']])
        tmp['resumen_total_num'] = to_number(tmp[resumen_cols['total']])

    agg_cols = {
        'ece_bool': 'max',
        'sinba_bool': 'max',
        'entidad': first_non_empty,
        'nombre_de_la_unidad': first_non_empty,
        **{f'{col}_num': 'max' for col in cols_num},
    }
    if resumen_cols:
        agg_cols.update({
            'resumen_ece_num': 'max',
            'resumen_sinba_num': 'max',
            'resumen_total_num': 'max',
        })

    by_clues = tmp.groupby('clues_imb', as_index=False).agg(agg_cols).rename(columns={
        'ece_bool': 'reporta_ece',
        'sinba_bool': 'reporta_sinba',
    })

    zeros_mask = (by_clues[[f'{col}_num' for col in cols_num]] == 0).all(axis=1)
    by_clues['cuatro_columnas_en_cero'] = zeros_mask

    only_ece = int(((by_clues['reporta_ece']) & (~by_clues['reporta_sinba'])).sum())
    both = int(((by_clues['reporta_ece']) & (by_clues['reporta_sinba'])).sum())
    only_sinba = int(((~by_clues['reporta_ece']) & (by_clues['reporta_sinba'])).sum())
    both_false = int(((~by_clues['reporta_ece']) & (~by_clues['reporta_sinba'])).sum())

    clues_cuatro_columnas_en_cero = int(zeros_mask.sum())
    total_clues_imb = int(by_clues['clues_imb'].nunique())
    total_clues_evaluadas = int(total_clues_imb - clues_cuatro_columnas_en_cero)
    no_reportaron = int(total_clues_imb - both_false)

    detalle_cols = [
        'clues_imb',
        'nombre_de_la_unidad',
        'entidad',
        'reporta_ece',
        'reporta_sinba',
        'cuatro_columnas_en_cero',
    ]
    if resumen_cols:
        detalle_cols.extend(['resumen_ece_num', 'resumen_sinba_num', 'resumen_total_num'])

    detalle_clues = by_clues[detalle_cols].copy()
    detalle_clues = detalle_clues.rename(columns={
        'reporta_ece': 'reporta_ece_bool',
        'reporta_sinba': 'reporta_sinba_bool',
        'resumen_ece_num': 'resumen_ece',
        'resumen_sinba_num': 'resumen_sinba',
        'resumen_total_num': 'resumen_total',
    })

    resumen_sistema = {
        'ece': int(by_clues['resumen_ece_num'].sum()) if resumen_cols else 0,
        'sinba': int(by_clues['resumen_sinba_num'].sum()) if resumen_cols else 0,
        'total': int(by_clues['resumen_total_num'].sum()) if resumen_cols else 0,
    }

    prev_cards = (previous_payload or {}).get('cards_clues', {})
    has_prev_cards = isinstance(prev_cards, dict) and len(prev_cards) > 0
    if has_prev_cards:
        delta_cards_clues = {
            'unicamente_en_ece': only_ece - to_int(prev_cards.get('unicamente_en_ece', only_ece)),
            'ambos_sistemas': both - to_int(prev_cards.get('ambos_sistemas', both)),
            'unicamente_en_sinba': only_sinba - to_int(prev_cards.get('unicamente_en_sinba', only_sinba)),
        }
    else:
        delta_cards_clues = {
            'unicamente_en_ece': 0,
            'ambos_sistemas': 0,
            'unicamente_en_sinba': 0,
        }

    prev_resumen = ((previous_payload or {}).get('metadata', {}) or {}).get('resumen_sistema', {})
    has_prev_resumen = isinstance(prev_resumen, dict) and len(prev_resumen) > 0
    if has_prev_resumen:
        delta_resumen_sistema = {
            'ece': resumen_sistema['ece'] - to_int(prev_resumen.get('ece', resumen_sistema['ece'])),
            'sinba': resumen_sistema['sinba'] - to_int(prev_resumen.get('sinba', resumen_sistema['sinba'])),
            'total': resumen_sistema['total'] - to_int(prev_resumen.get('total', resumen_sistema['total'])),
        }
    else:
        delta_resumen_sistema = {
            'ece': 0,
            'sinba': 0,
            'total': 0,
        }

    return {
        'indicador': indicador,
        'cards_clues': {
            'unicamente_en_ece': only_ece,
            'ambos_sistemas': both,
            'unicamente_en_sinba': only_sinba,
        },
        'metadata': {
            'total_clues_imb': total_clues_imb,
            'total_clues_evaluadas': total_clues_evaluadas,
            'clues_con_cuatro_columnas_en_cero': clues_cuatro_columnas_en_cero,
            'clues_sin_reporte_ambos': both_false,
            'no_reportaron': no_reportaron,
            'resumen_sistema': resumen_sistema,
            'delta_cards_clues': delta_cards_clues,
            'delta_resumen_sistema': delta_resumen_sistema,
            'columnas_numericas_fuente': cols_num,
            'columnas_fuente': required_cols,
        },
        'detalle_clues': detalle_clues.to_dict(orient='records'),
    }

consultas_cards = build_cards_payload(
    df=informe,
    indicador='consultas',
    cols_num=[
        'consultas_reportadas_ece',
        'consultas_incorporadas_ece',
        'consultas_reportadas_sinba',
        'consultas_totales',
    ],
    col_bool_ece='reporta_consulta_ece',
    col_bool_sinba='reporta_consulta_sinba',
    resumen_cols={
        'ece': 'consultas_reportadas_ece',
        'sinba': 'consultas_reportadas_sinba',
        'total': 'consultas_totales',
    },
    previous_payload=prev_infraestructura_cards.get('consultas'),
)

pqx_cards = build_cards_payload(
    df=informe,
    indicador='procedimientos_quirurgicos',
    cols_num=[
        'pqx_reportados_ece',
        'pqx_incorporados_ece',
        'pqx_reportados_sinba',
        'pqx_totales',
    ],
    col_bool_ece='reporta_pqx_ece',
    col_bool_sinba='reporta_pqx_sinba',
    resumen_cols={
        'ece': 'pqx_reportados_ece',
        'sinba': 'pqx_reportados_sinba',
        'total': 'pqx_totales',
    },
    previous_payload=prev_infraestructura_cards.get('procedimientos_quirurgicos'),
)

egresos_cards = build_cards_payload(
    df=informe,
    indicador='egresos_hospitalarios',
    cols_num=[
        'egresos_reportados_ece',
        'egresos_incorporados_ece',
        'egresos_reportados_sinba',
        'egresos_totales',
    ],
    col_bool_ece='reporta_egreso_ece',
    col_bool_sinba='reporta_egreso_sinba',
    resumen_cols={
        'ece': 'egresos_reportados_ece',
        'sinba': 'egresos_reportados_sinba',
        'total': 'egresos_totales',
    },
    previous_payload=prev_infraestructura_cards.get('egresos_hospitalarios'),
)

infraestructura_cards = {
    'indicador': 'infraestructura_cards',
    'consultas': consultas_cards,
    'procedimientos_quirurgicos': pqx_cards,
    'egresos_hospitalarios': egresos_cards,
}

In [11]:
import json
from pathlib import Path

base_output = Path(r"C:\Users\jose.valdez\Downloads\reporteador\reporte-_angeles\public")
base_output.mkdir(parents=True, exist_ok=True)

infra_output_path = base_output / 'infraestructura_cards.json'
with infra_output_path.open('w', encoding='utf-8') as f:
    json.dump(infraestructura_cards, f, ensure_ascii=False, indent=2)

# Compatibilidad con la conexion previa de Procedimientos Quirurgicos
pqx_output_path = base_output / 'procedimientos_quirurgicos_cards.json'
with pqx_output_path.open('w', encoding='utf-8') as f:
    json.dump(pqx_cards, f, ensure_ascii=False, indent=2)

# Historico semanal en un solo parquet (una fila por indicador y semana)
hist_dir = base_output / 'historico'
hist_dir.mkdir(parents=True, exist_ok=True)
hist_path = hist_dir / 'infraestructura_hist.parquet'

fecha_corte = pd.Timestamp.now().normalize()
semana_inicio = fecha_corte - pd.Timedelta(days=fecha_corte.weekday())
semana_fin = semana_inicio + pd.Timedelta(days=6)

def to_int(value: object) -> int:
    try:
        return int(float(value))
    except Exception:
        return 0

rows = []
for indicador_key in ['consultas', 'procedimientos_quirurgicos', 'egresos_hospitalarios']:
    payload = infraestructura_cards.get(indicador_key, {}) or {}
    cards = payload.get('cards_clues', {}) or {}
    meta = payload.get('metadata', {}) or {}
    resumen = meta.get('resumen_sistema', {}) or {}
    delta_cards = meta.get('delta_cards_clues', {}) or {}
    delta_resumen = meta.get('delta_resumen_sistema', {}) or {}

    rows.append({
        'fecha_corte': fecha_corte,
        'semana_inicio': semana_inicio,
        'semana_fin': semana_fin,
        'indicador': indicador_key,
        'unicamente_en_ece': to_int(cards.get('unicamente_en_ece', 0)),
        'ambos_sistemas': to_int(cards.get('ambos_sistemas', 0)),
        'unicamente_en_sinba': to_int(cards.get('unicamente_en_sinba', 0)),
        'total_clues_evaluadas': to_int(meta.get('total_clues_evaluadas', 0)),
        'no_reportaron': to_int(meta.get('no_reportaron', 0)),
        'resumen_ece': to_int(resumen.get('ece', 0)),
        'resumen_sinba': to_int(resumen.get('sinba', 0)),
        'resumen_total': to_int(resumen.get('total', 0)),
        'delta_unicamente_en_ece': to_int(delta_cards.get('unicamente_en_ece', 0)),
        'delta_ambos_sistemas': to_int(delta_cards.get('ambos_sistemas', 0)),
        'delta_unicamente_en_sinba': to_int(delta_cards.get('unicamente_en_sinba', 0)),
        'delta_resumen_ece': to_int(delta_resumen.get('ece', 0)),
        'delta_resumen_sinba': to_int(delta_resumen.get('sinba', 0)),
        'delta_resumen_total': to_int(delta_resumen.get('total', 0)),
    })

new_week_df = pd.DataFrame(rows)

if hist_path.exists():
    hist_df = pd.read_parquet(hist_path)
    if not hist_df.empty:
        hist_df['fecha_corte'] = pd.to_datetime(hist_df['fecha_corte']).dt.normalize()

        if 'semana_inicio' in hist_df.columns:
            hist_df['semana_inicio'] = pd.to_datetime(hist_df['semana_inicio']).dt.normalize()
        else:
            hist_df['semana_inicio'] = hist_df['fecha_corte'] - pd.to_timedelta(hist_df['fecha_corte'].dt.weekday, unit='D')

        if 'semana_fin' in hist_df.columns:
            hist_df['semana_fin'] = pd.to_datetime(hist_df['semana_fin']).dt.normalize()
        else:
            hist_df['semana_fin'] = hist_df['semana_inicio'] + pd.Timedelta(days=6)

        # Si se corre varias veces en la misma semana, sustituye por el corte mas reciente.
        hist_df = hist_df[hist_df['semana_inicio'] != semana_inicio]

    out_df = pd.concat([hist_df, new_week_df], ignore_index=True)
else:
    out_df = new_week_df.copy()

# Garantiza una sola fila por indicador por semana, conservando la mas reciente.
out_df = out_df.sort_values(['semana_inicio', 'indicador', 'fecha_corte']).drop_duplicates(
    subset=['semana_inicio', 'indicador'],
    keep='last'
).reset_index(drop=True)

out_df.to_parquet(hist_path, index=False)

infra_output_path, pqx_output_path, hist_path, out_df.tail(3)

(WindowsPath('C:/Users/jose.valdez/Downloads/reporteador/reporte-_angeles/public/infraestructura_cards.json'),
 WindowsPath('C:/Users/jose.valdez/Downloads/reporteador/reporte-_angeles/public/procedimientos_quirurgicos_cards.json'),
 WindowsPath('C:/Users/jose.valdez/Downloads/reporteador/reporte-_angeles/public/historico/infraestructura_hist.parquet'),
   fecha_corte                   indicador  unicamente_en_ece  ambos_sistemas  \
 0  2026-08-12                   consultas                  8              69
 1  2026-08-12       egresos_hospitalarios                  8              52
 2  2026-08-12  procedimientos_quirurgicos                  9              39

    unicamente_en_sinba  total_clues_evaluadas  no_reportaron  resumen_ece  \
 0                  495                    588            572       233974
 1                  479                    585            539        34830
 2                  426                    537            474        12838

    resumen_sinba  resumen_total  delta_unicamente_en_ece  \
 0        6287971        6388333                        0
 1         867743         886452                        0
 2         513479         520675                        0

    delta_ambos_sistemas  delta_unicamente_en_sinba  delta_resumen_ece  \
 0                     0                          0                  0
 1                     0                          0                  0
 2                     0                          0                  0

    delta_resumen_sinba  delta_resumen_total semana_inicio semana_fin
 0                    0                    0    2026-08-10 2026-08-16
 1                    0                    0    2026-08-10 2026-08-16
 2                    0                    0    2026-08-10 2026-08-16  )